# -*- coding: utf-8 -*-
"""Copy of Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DFuldnb_lyM0YpQ09MZtwDck2AfJr_ai

Assignment No 1 Variables
"""

num1 = 10
num2 = 8
print("sum:" , num1 + num2)
print("Difference:" , num1 - num2)
print("Multiple:" , num1 * num2)
print("Division:" , num1 / num2)

"""Assign No 2 Personal info card"""

name = "Aiman"
age = 23
hobby = "Reading Novel"
print("Hi"+ "My name is" +name+ "I am " +str(age)+ "years old." "My Hobby is"+hobby )

"""Assignment 3: Temperature Converter
*Objective:* Use expressions.
*Task:*
Convert Celsius to Fahrenheit using the formula: (celsius * 9/5) + 32.
"""

Celsius= 25
Fahrenheit= (Celsius * 9/5) + 32
print("Temperature in Fahrenheit:", Fahrenheit)



"""Assignment 4: Area of Rectangle

*Objective:* Logical math with variables.
*Task:*
Calculate the area of a rectangle using the formula: length * width.

"""

Length = 5
Width = 10


Area = Length*Width
print("Area of rectangle:",Area)

"""Assignment 5: Salary Increment

*Objective:* Practice updating variable values.
*Task:*
Store a salary in a variable and then increase it by 10%. Print both the old and new salary.

"""

salary = 50000

new_salary = salary + (salary * 0.10)

print("Old Salary:", salary)
print("New Salary after 10% increase:", new_salary)

"""Topic 2: TUPLES
Make a tuple marks = (78, 82, 90, 67, 88).
Print the highest and lowest marks using the max() and min() functions.

"""

Marks = (78,82,90,67,88)
print("Highest Marks:",max(Marks))
print("Lowest Marks:",min(Marks))

"""Assignment 1: Favorite Fruits

*Task:*
Create a tuple of 5 fruits and print:
*   The first fruit
*   The last fruit
*   The total number of fruits

"""

fruit=("Apple","Banana","Mango","Grapes","Orange")
print(fruit[0])
print(fruit[-1])
print(len(fruit))

"""Create a tuple of 10 numbers and print:
*   The first 3 numbers
*   The last 3 numbers
*   The middle 4 numbers
"""

numbers = (10, 20, 30, 40, 50, 60, 70, 80, 90, 100)
print("First 3 numbers:", numbers[:3])
print("Last 3 numbers:", numbers[-3:])
print("Middle 4 numbers:", numbers[2:6])

"""Create a tuple of city names and print:
*   The city at index 2
*   The city at index -1 (which is the last city)

"""

City=("karachi","Islamabad")
print(City[-1])

"""*Task:*
Create a tuple with repeating colors: ('red', 'blue', 'red', 'green', 'red').
Print how many times "red" appears in the tuple and find its first index.

"""

colors= ('red', 'blue', 'red', 'green', 'red')
print(colors.count("red"))
print(colors.index("red"))

"""Topic 3: LISTS (5 Assignments)

Make a list of 5 student names.
Then, add one new name to the list using .append() and remove one existing name using .remove().
"""

studentname=("Aiman","Ahmed","Ibrahim","Fatiam","Ammad")
studentname=list(studentname)
studentname.append("Ali")
print(studentname)
studentname.remove("Ahmed")
print(studentname)

"""Make a list of 5 grocery items.
Replace one item (e.g., change 'milk' to 'butter').
Print the updated list and the total number of items in the list.

"""

Groceryitem=("Milk","Buttre","Cheese","Eggs","Rice")
print(Groceryitem)
Groceryitem=list(Groceryitem)
Groceryitem.remove("Milk")
Groceryitem.insert(0,"Wheat")
print(Groceryitem)

"""Make a list of random numbers.
Print the list before and after sorting it using the .sort() method.
"""

Numbers=(23,45,67,98,65,32)
print(Numbers)
Numbers=list(Numbers)
Numbers.sort()
print(Numbers)

"""Store 4 movie names in a list.
Print:
*   The first two movies
*   The last movie
*   The total number of movies
"""

MovieName=("Saiyara","Royal Casino","Fast and Fourius","Nun")
print(MovieName[:2])
print(MovieName[-1])
print(len(MovieName))

"""Make a list of numbers [5, 10, 15, 20].
Print:
*   The total sum of the numbers using sum()
*   The average of the numbers
"""

numbers = [5, 10, 15, 20]
total = sum(numbers)
average = total / len(numbers)

print("Total Sum:", total)
print("Average:", average)

"""Topic 4: SETS (5 Assignments)

Assignment 1: Unique Numbers

*Task:*
Create a set with some duplicate numbers (e.g., {1, 2, 2, 3, 4, 4, 5}).
Print the set to show how duplicates are automatically removed.
"""

Sets={1, 2, 2, 3, 4, 4, 5}
print(Sets)

"""Assignment 2: Set Operations

Create two sets:
A = {1, 2, 3, 4}
B = {3, 4, 5, 6}

Print their:
*   Union (all unique elements from both sets)
*   Intersection (elements common to both sets)
*   Difference (elements in A but not in B)
"""

set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}

result = set1.union(set2)
print("Union of sets:", result)

result = set1.intersection(set2)
print("Intersection of sets:", result)


result = set1.difference(set2)
print("Difference of sets:", result)

"""Assignment 3: Adding & Removing

Create a set {2, 4, 6}.
Add the number 8 to the set, then remove the number 4.
Print the updated set.
"""

set ={2, 4, 6}
set.add(8)
print(set)
set.remove(4)
print(set)

"""Assignment 4: Membership Check

Check if a specific number (e.g., 5) exists in the set {1, 2, 3, 4, 5} using the in keyword. Print True or False.
"""

set={1, 2, 3, 4, 5}
print(5 in set)

"""Assignment 5: Convert List to Set

Given a list [1, 2, 2, 3, 4, 4, 5].
Convert this list to a set to automatically remove duplicates. Print both the original list and the resulting set.
"""

# Given list
numbers = [1, 2, 2, 3, 4, 4, 5]

# Converting list to set (removes duplicates)
unique_numbers = set(numbers)

# Printing results
print("Original List:", numbers)
print("Set (duplicates removed):", unique_numbers)

"""Topic 5: DICTIONARIES (5 Assignments)

Assignment 1: Student Info

*Task:*
Create a dictionary named student with the following information:
python
student = {
  "name": "Ali",
  "age": 20,
  "grade": "A"
}

Print a sentence using this dictionary: Ali is 20 years old and got grade A.
"""

student = {
    "name": "Aiman",
    "age": 23,
    "grade": "A"
}
print(student["name"],"is",student["age"],"years old and got grade",student["grade"])

"""Assignment 2: Update Dictionary

*Task:*
Start with the following dictionary:
python
car = {"brand": "Toyota", "year": 2020}

Add a new key color with a value (e.g., "Red").
Update the year to 2022.
Print the updated dictionary.
"""

car = {"brand": "Toyota", "year": 2020}

car["color"] = "Red"

car["year"] = 2022

print(car)

"""Assignment 3: Loop Through Dictionary

Create a dictionary of 3 countries with their capitals (e.g., Pakistan: Islamabad, Turkey: Ankara, Japan: Tokyo).
Loop through the dictionary and print each country and its capital in the format: Country → Capital.
"""

Countries={
    "Pakistan":"Islamabad",
    "Turkey":"Ankara",
    "Japan":"Tokyo"
}
for country, capital in Countries.items():
    print(country, "→", capital)

"""Assignment 4: Dictionary of Prices

Create a dictionary of 3 products and their prices (e.g., {"apple": 1.5, "banana": 0.75, "orange": 1.2}).
Ask the user which product's price they want to see and display it.
"""

products={
    "apple": 1.5,
    "banana": 0.75,
    "orange": 1.2
}
product_name = input("Enter the name of the product: ")

if product_name in products:
    price = products[product_name]
    print(f"The price of {product_name} is ${price:.2f}")

"""Assignment 5: Nested Dictionary

Create a dictionary named students with nested dictionaries for each student's information:
python
students = {
  "Ali": {"age": 18, "grade": "A"},
  "Sara": {"age": 19, "grade": "B"}
}

Loop through the students dictionary and print each student's name along with their grade.
"""

students = {
     "Ali": {"age": 18, "grade": "A"},
     "Sara": {"age": 19, "grade": "B"}
     }
for student, info in students.items():
    grade = info["grade"]
    print(f"{student}'s grade is {grade}")